export enum WEBHOOK_QUEUE {
    WEBHOOK_DEPOSIT = 'WEBHOOK_DEPOSIT',
    WEBHOOK_WITHDRAW = 'WEBHOOK_WITHDRAW',
    WEBHOOK_CREATE_VAULT = 'WEBHOOK_CREATE_VAULT',
    VALIDATOR_WEBHOOK_UPDATE_VAULT = 'VALIDATOR_WEBHOOK_UPDATE_VAULT',
    WEBHOOK_WITHDRAWAL_REQUESTED = 'WEBHOOK_WITHDRAWAL_REQUESTED',
    WEBHOOK_WITHDRAWAL_CLAIMED = 'WEBHOOK_WITHDRAWAL_CLAIMED',
    WEBHOOK_TRANSFER_FUND_APEX = 'WEBHOOK_TRANSFER_FUND_APEX',
}
